[
  {
    name: "setprefix",
    aliases: ["sp", "setp"],
    usage: "No usage provided.",
    description: "Set your server's custom prefix!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 20,
    userPermissions: ["MANAGE_MESSAGES", "MANAGE_CHANNELS"],
    clientPermissions: null,
  },
  {
    name: "connect4",
    aliases: ["c4", "connectfour"],
    usage: "No usage provided.",
    description: "Play the connect four game!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "gend",
    aliases: [null, "giveawayend", "g-end", "g-end", "gfinish"],
    usage: "No usage provided.",
    description: "Ends a giveaway.",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "beautify",
    aliases: null,
    usage: "No usage provided.",
    description: "Make you more beautiful :D",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "blur",
    aliases: null,
    usage: "No usage provided.",
    description: "Blur you!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "pixelate",
    aliases: null,
    usage: "No usage provided.",
    description: "Shows a pixelated version of someone's avatar!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "rainbow",
    aliases: null,
    usage: "No usage provided.",
    description: "Makes someone's avatar rainbow!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "rip",
    aliases: null,
    usage: "No usage provided.",
    description: "Shows you someone's grave!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "trigger",
    aliases: null,
    usage: "No usage provided.",
    description: "Shows a triggered version of someone's avatar!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "wanted",
    aliases: null,
    usage: "No usage provided.",
    description: "Makes someone's avatar wanted.",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: 5,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "botinfo",
    aliases: ["info", "bi"],
    usage: "No usage provided.",
    description: "About the bot!",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "lock",
    aliases: null,
    usage: "No usage provided.",
    description: "Locks down a channel",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "filters",
    aliases: ["filter"],
    usage: "No usage provided.",
    description: "No description provided.",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "eval",
    aliases: null,
    usage: "No usage provided.",
    description: "Evaluates arbituary JavaScript.",
    ownerOnly: true,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "exec",
    aliases: null,
    usage: "No usage provided.",
    description:
      "Executes the provided code in the bash console and shows the output.",
    ownerOnly: true,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "reboot",
    aliases: null,
    usage: "No usage provided.",
    description: "reboot the bot.",
    ownerOnly: false,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
  {
    name: "reload",
    aliases: null,
    usage: "No usage provided.",
    description: "Reloads a command",
    ownerOnly: true,
    examples: "No example provided.",
    cooldown: null,
    userPermissions: null,
    clientPermissions: null,
  },
];
