module.exports = {
	ADMINISTRATOR: "Administrator",
	VIEW_AUDIT_LOG: "View Audit Log",
	VIEW_GUILD_INSIGHTS: "View Server Insights",
	MANAGE_GUILD: "Manage Server",
	MANAGE_ROLES: "Manage Roles",
	MANAGE_CHANNELS: "Manage Channels",
	KICK_MEMBERS: "Kick Members",
	BAN_MEMBERS: "Ban Members",
	CREATE_INSTANT_INVITE: "Create Invite",
	CHANGE_NICKNAME: "Change Nickname",
	MANAGE_NICKNAMES: "Manage Nicknames",
	MANAGE_EMOJIS: "Manage Emojis",
	MANAGE_WEBHOOKS: "Manage Webhooks",
	VIEW_CHANNEL: "Read Text Channels & See Voice Channels",
	SEND_MESSAGES: "Send Messages",
	SEND_TTS_MESSAGES: "Send TTS Messages",
	MANAGE_MESSAGES: "Manage Messages",
	EMBED_LINKS: "Embed Links",
	ATTACH_FILES: "Attach Files",
	READ_MESSAGE_HISTORY: "Read Message History",
	MENTION_EVERYONE: "Mention @everyone, @here, and All Roles",
	USE_EXTERNAL_EMOJIS: "Use External Emojis",
	ADD_REACTIONS: "Add Reactions",
	CONNECT: "Connect",
	SPEAK: "Speak",
	STREAM: "Video",
	MUTE_MEMBERS: "Mute Members",
	DEAFEN_MEMBERS: "Deafen Members",
	MOVE_MEMBERS: "Move Members",
	USE_VAD: "Use Voice Activity",
	PRIORITY_SPEAKER: "Priority Speaker",
    MANAGE_EMOJIS_AND_STICKERS: "Manage Emojis and Stickers",
USE_APPLICATION_COMMANDS: "Use Application Commands",
REQUEST_TO_SPEAK: "Request to Speak",
MANAGE_EVENTS: "Manage Events",
MANAGE_THREADS: "Manage Threads",
USE_PUBLIC_THREADS: "Use Public Threads",
CREATE_PUBLIC_THREADS: "Create Public Threads",
USE_PRIVATE_THREADS: "Use Private Threads",
CREATE_PRIVATE_THREADS: "Create Private Threads",
USE_EXTERNAL_STICKERS: "Use External Stickers",
SEND_MESSAGES_IN_THREADS: "Send Messages in Threads",
START_EMBEDDED_ACTIVITIES: "Start Embedded Activities",
MODERATE_MEMBERS: "Moderate Members",
};
